# .github/workflows/deploy.yml

name: prototype 1 deploy to GitHub Pages

# 1) test1 브랜치에 push 될 때만 동작
on:
  push:
    branches: [test1]

# 2) 최소 권한만 부여
permissions:
  contents: read   # 코드 읽기
  pages: write     # Pages 배포
  id-token: write  # OIDC 토큰

jobs:
  # 3) 빌드 작업
  build:
    runs-on: ubuntu-latest
    steps:
      # 3-1) 리포지토리 복제
      - uses: actions/checkout@v4

      # 3-2) Node.js 설치 (v18)
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3-3) 의존성 설치
      - run: npm ci

      # 3-4) web1, web2 폴더 각각 빌드
      - run: npm run --prefix web1 build
      - run: npm run --prefix web2 build

      # 3-5) 빌드 결과를 dist/web1, dist/web2 로 모으기
      - run: |
          mkdir -p dist
          cp -r web1/build dist/web1
          cp -r web2/build dist/web2

      # 3-6) Pages용 아티팩트 업로드
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist

  # 4) 배포 작업 (build 성공 후 실행)
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # 4-1) 업로드된 아티팩트를 실제 Pages에 배포
      - id: deployment
        uses: actions/deploy-pages@v4
